# Generated by Django 4.2.16 on 2026-07-18 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('content', models.TextField(blank=True, default='')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('expires_at', models.DateTimeField()),
                ('burn_after_read', models.BooleanField(default=False)),
                ('is_burned', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('is_searchable', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YjsUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clipboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yjs_updates', to='clipboard.clipboard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClipboardViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('clipboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='clipboard.clipboard')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
