# Generated by Django 4.2.16 on 2026-07-18 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='delete_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
